sudo: required

services:
  - docker

before_install:
  - docker build -t reactapp -f  Dockerfile.dev .

script:
  - docker run -e CI=true reactapp npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "docker-react-app"
  env: "example-app-environment"
  bucket_name: "elasticbeanstalk-us-east-2-841160614926"
  bucket_path: "docker-react-app"
  on:
    branch: master
